[project]
name = "quantum-neutral-atoms"
version = "1.0.0"
description = "Quantum Neutral Atoms Research Library"
authors = [
    { name = "Dr. Boris Milanovic", email = "dr.milanovic@proton.me" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.2.0",
    "pasqal-cloud>=0.22.0",
    "qadence[visualization]>=1.11.5",
    "sympy>=1.13.3",
    "torch>=2.12.0",
]
